version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8085:8080"  # Host port:Container port
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_USER=admin  # Replace with your desired username
      - JENKINS_PASS=admin123  # Replace with your desired password
    env_file:
      - jenkins.env

volumes:
  jenkins_home:
