services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8085:8080"  # Host port:Container port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DOCKER_GID=${DOCKER_GID}
    env_file:
      - ./jenkins.env
    group_add:
      - ${DOCKER_GID}

volumes:
  jenkins_home:
